### ISSUE TITLE
AttributeError: 'module' object has no attribute 'to_unicode'

### ISSUE THREAD

**Issue by mousewu** [marinkaz/ohmnet#2]
When I run this code, the following error occurs. Could you please help me to figure out what's wrong?

INFO:ohmnet.gensimmod.model.word2vec:loading projection weights from emb/tmp.emb
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main(args)
  File "main.py", line 62, in main
    on.embed_multilayer()
  File "/Work/deeplearning/network-analysis/ohmnet/ohmnet/ohmnet.py", line 200, in embed_multilayer
    self.model.load_parent_word2vec_format(fname=tmp_fname)
  File "/Work/deeplearning/network-analysis/ohmnet/ohmnet/gensimmod/model/word2vec.py", line 1235, in load_parent_word2vec_format
    header = utils.to_unicode(fin.readline(), encoding=encoding)
AttributeError: 'module' object has no attribute 'to_unicode'

**Comment by marinkaz** [comment]
Fixed, thanks!
